"""initial_schema

Revision ID: 972727cd371f
Revises: 
Create Date: 2026-05-13 16:22:27.127780

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '972727cd371f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('acc_submissions', 'polo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('acc_submissions', 'periodo',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('alertas_academicos', 'destination_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'docentes'::character varying"))
    op.alter_column('alertas_academicos', 'destination_emails',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('estagio_submissions', 'polo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('estagio_submissions', 'periodo',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('requerimento_tcc_submissions', 'resumo',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('tcc_submissions', 'polo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('tcc_submissions', 'periodo',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tcc_submissions', 'periodo',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('tcc_submissions', 'polo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('requerimento_tcc_submissions', 'resumo',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('estagio_submissions', 'periodo',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('estagio_submissions', 'polo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('alertas_academicos', 'destination_emails',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('alertas_academicos', 'destination_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'docentes'::character varying"))
    op.alter_column('acc_submissions', 'periodo',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('acc_submissions', 'polo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###
