version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8501:8501"
    env_file:
      - ../.env.example
    volumes:
      - ..:/app
