name: CI

# CI desabilitado temporariamente - reativar quando testes forem implementados
on:
  workflow_dispatch:  # Permite execução manual apenas

# on:
#   pull_request:
#   push:
#     branches:
#       - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run tests
        run: pytest
