[theme]
primaryColor = "#7c3aed"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#1a0d2e"
font = "sans serif"
base = "light"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
port = 8501
# Aumentar limite de upload para 200MB para resolver erro 413
maxUploadSize = 200

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true
toolbarMode = "minimal"

[ui]
hideTopBar = false
